### ISSUE TITLE
Error in catkin_make

### ISSUE THREAD

**Issue by siddharthumakarthikeyan** [SaumilShah66/CDPR-Robot-modelling-project#1]
Hello Saumil,
Thanks for sharing this amazing work. I faced an error while doing catkin_make.
![Screenshot from 2021-06-14 01-43-11](https://user-images.githubusercontent.com/82173562/121820774-36c42000-ccb2-11eb-8e34-cb96b49dfcaf.png)

The procedure I followed is
1. mkdir catkin_ws
2. cd catkin_ws
3. git clone https://github.com/SaumilShah66/CDPR-Robot-modelling-project.git src
4. source /opt/ros/noetic/setup.bash
5. catkin_make (Here I got this error).

Would like to know how to pass this. Thanks.

**Comment by SaumilShah66** [comment]
I am sorry I am not actively maintaining this. You can find log2plot module here https://github.com/oKermorgant/log2plot.
Visp is the ROS package http://wiki.ros.org/visp.
Try with these two.

**Comment by siddharthumakarthikeyan** [comment]
Thanks for your reply.!
